# Generated by Django 4.1.7 on 2023-06-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endvr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Btech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class_10th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('english', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class_11th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('english', models.IntegerField()),
                ('computer_science', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('physical_education', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class_12th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('english', models.IntegerField()),
                ('computer_science', models.IntegerField()),
                ('biology', models.IntegerField()),
                ('physical_education', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class_9th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('maths', models.IntegerField()),
                ('science', models.IntegerField()),
                ('english', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('social_science', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('class_9th', models.CharField(max_length=100)),
                ('class_10th', models.CharField(max_length=100)),
                ('class_11th', models.CharField(max_length=100)),
                ('class_12th', models.CharField(max_length=100)),
                ('bsc', models.CharField(max_length=100)),
                ('btech', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('skill_1', models.CharField(max_length=100)),
                ('skill_2', models.CharField(max_length=100)),
                ('skill_3', models.CharField(max_length=100)),
            ],
        ),
    ]
